const INCREMENT_COUNTER = "INCREMENT_COUNTER"
const DECREMENT_COUNTER = "DECREMENT_COUNTER"
const DATA_CLEAR_COUNTER = "DATA_CLEAR_COUNTER"
export {
    DECREMENT_COUNTER,
    INCREMENT_COUNTER,
    DATA_CLEAR_COUNTER
}